/**
 * Every indexable page, used by several test files. Playwright cannot import the JSON
 * dictionaries behind src/i18n, so this list is kept by hand; a unit test
 * (src/i18n/pages.test.ts) fails if it ever drifts from the route table.
 */
export const PAGES = [
  { key: "home", path: "/", lang: "en", alt: "/es", calc: false },
  { key: "home", path: "/es", lang: "es", alt: "/", calc: false },
  { key: "loan", path: "/loan-calculator", lang: "en", alt: "/es/calculadora-de-prestamos", calc: true },
  { key: "loan", path: "/es/calculadora-de-prestamos", lang: "es", alt: "/loan-calculator", calc: true },
  {
    key: "investment",
    path: "/investment-calculator",
    lang: "en",
    alt: "/es/calculadora-de-inversion",
    calc: true,
  },
  {
    key: "investment",
    path: "/es/calculadora-de-inversion",
    lang: "es",
    alt: "/investment-calculator",
    calc: true,
  },
  {
    key: "compound",
    path: "/compound-interest-calculator",
    lang: "en",
    alt: "/es/calculadora-de-interes-compuesto",
    calc: true,
  },
  {
    key: "compound",
    path: "/es/calculadora-de-interes-compuesto",
    lang: "es",
    alt: "/compound-interest-calculator",
    calc: true,
  },
  {
    key: "mortgage",
    path: "/mortgage-calculator",
    lang: "en",
    alt: "/es/calculadora-de-hipoteca",
    calc: true,
  },
  {
    key: "mortgage",
    path: "/es/calculadora-de-hipoteca",
    lang: "es",
    alt: "/mortgage-calculator",
    calc: true,
  },
  {
    key: "affordability",
    path: "/home-affordability-calculator",
    lang: "en",
    alt: "/es/calculadora-de-capacidad-hipotecaria",
    calc: true,
  },
  {
    key: "affordability",
    path: "/es/calculadora-de-capacidad-hipotecaria",
    lang: "es",
    alt: "/home-affordability-calculator",
    calc: true,
  },
  {
    key: "creditCard",
    path: "/credit-card-payoff-calculator",
    lang: "en",
    alt: "/es/calculadora-de-pago-de-tarjeta-de-credito",
    calc: true,
  },
  {
    key: "creditCard",
    path: "/es/calculadora-de-pago-de-tarjeta-de-credito",
    lang: "es",
    alt: "/credit-card-payoff-calculator",
    calc: true,
  },
  {
    key: "fd",
    path: "/fixed-deposit-calculator",
    lang: "en",
    alt: "/es/calculadora-de-plazo-fijo",
    calc: true,
  },
  {
    key: "fd",
    path: "/es/calculadora-de-plazo-fijo",
    lang: "es",
    alt: "/fixed-deposit-calculator",
    calc: true,
  },
  {
    key: "rd",
    path: "/recurring-deposit-calculator",
    lang: "en",
    alt: "/es/calculadora-de-deposito-recurrente",
    calc: true,
  },
  {
    key: "rd",
    path: "/es/calculadora-de-deposito-recurrente",
    lang: "es",
    alt: "/recurring-deposit-calculator",
    calc: true,
  },
  {
    key: "simple",
    path: "/simple-interest-calculator",
    lang: "en",
    alt: "/es/calculadora-de-interes-simple",
    calc: true,
  },
  {
    key: "simple",
    path: "/es/calculadora-de-interes-simple",
    lang: "es",
    alt: "/simple-interest-calculator",
    calc: true,
  },
  { key: "cagr", path: "/cagr-calculator", lang: "en", alt: "/es/calculadora-de-cagr", calc: true },
  { key: "cagr", path: "/es/calculadora-de-cagr", lang: "es", alt: "/cagr-calculator", calc: true },
  {
    key: "retirement",
    path: "/retirement-calculator",
    lang: "en",
    alt: "/es/calculadora-de-jubilacion",
    calc: true,
  },
  {
    key: "retirement",
    path: "/es/calculadora-de-jubilacion",
    lang: "es",
    alt: "/retirement-calculator",
    calc: true,
  },
  {
    key: "savings",
    path: "/savings-goal-calculator",
    lang: "en",
    alt: "/es/calculadora-de-meta-de-ahorro",
    calc: true,
  },
  {
    key: "savings",
    path: "/es/calculadora-de-meta-de-ahorro",
    lang: "es",
    alt: "/savings-goal-calculator",
    calc: true,
  },
  {
    key: "inflation",
    path: "/inflation-calculator",
    lang: "en",
    alt: "/es/calculadora-de-inflacion",
    calc: true,
  },
  {
    key: "inflation",
    path: "/es/calculadora-de-inflacion",
    lang: "es",
    alt: "/inflation-calculator",
    calc: true,
  },
  { key: "about", path: "/about", lang: "en", alt: "/es/acerca-de", calc: false },
  { key: "about", path: "/es/acerca-de", lang: "es", alt: "/about", calc: false },
  { key: "terms", path: "/terms", lang: "en", alt: "/es/terminos", calc: false },
  { key: "terms", path: "/es/terminos", lang: "es", alt: "/terms", calc: false },
  { key: "disclaimer", path: "/disclaimer", lang: "en", alt: "/es/descargo-de-responsabilidad", calc: false },
  { key: "disclaimer", path: "/es/descargo-de-responsabilidad", lang: "es", alt: "/disclaimer", calc: false },
  { key: "privacy", path: "/privacy", lang: "en", alt: "/es/privacidad", calc: false },
  { key: "privacy", path: "/es/privacidad", lang: "es", alt: "/privacy", calc: false },
] as const;

/** Calculator pages only. */
export const CALC_PAGES = PAGES.filter((p) => p.calc);
