/**
 * Every indexable page, used by several test files. Playwright cannot import the JSON
 * dictionaries behind src/i18n, so this list is kept by hand; a unit test
 * (src/i18n/pages.test.ts) fails if it ever drifts from the route table.
 * `alt` is the same page in the next language (en → es → de → en), used by the switcher test.
 */
export const PAGES = [
  { key: "home", path: "/", lang: "en", alt: "/es", altLang: "es", calc: false },
  { key: "home", path: "/es", lang: "es", alt: "/de", altLang: "de", calc: false },
  { key: "home", path: "/de", lang: "de", alt: "/", altLang: "en", calc: false },
  {
    key: "loan",
    path: "/loan-calculator",
    lang: "en",
    alt: "/es/calculadora-de-prestamos",
    altLang: "es",
    calc: true,
  },
  {
    key: "loan",
    path: "/es/calculadora-de-prestamos",
    lang: "es",
    alt: "/de/kreditrechner",
    altLang: "de",
    calc: true,
  },
  { key: "loan", path: "/de/kreditrechner", lang: "de", alt: "/loan-calculator", altLang: "en", calc: true },
  {
    key: "investment",
    path: "/investment-calculator",
    lang: "en",
    alt: "/es/calculadora-de-inversion",
    altLang: "es",
    calc: true,
  },
  {
    key: "investment",
    path: "/es/calculadora-de-inversion",
    lang: "es",
    alt: "/de/sparplanrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "investment",
    path: "/de/sparplanrechner",
    lang: "de",
    alt: "/investment-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "compound",
    path: "/compound-interest-calculator",
    lang: "en",
    alt: "/es/calculadora-de-interes-compuesto",
    altLang: "es",
    calc: true,
  },
  {
    key: "compound",
    path: "/es/calculadora-de-interes-compuesto",
    lang: "es",
    alt: "/de/zinseszinsrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "compound",
    path: "/de/zinseszinsrechner",
    lang: "de",
    alt: "/compound-interest-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "mortgage",
    path: "/mortgage-calculator",
    lang: "en",
    alt: "/es/calculadora-de-hipoteca",
    altLang: "es",
    calc: true,
  },
  {
    key: "mortgage",
    path: "/es/calculadora-de-hipoteca",
    lang: "es",
    alt: "/de/baufinanzierungsrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "mortgage",
    path: "/de/baufinanzierungsrechner",
    lang: "de",
    alt: "/mortgage-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "affordability",
    path: "/home-affordability-calculator",
    lang: "en",
    alt: "/es/calculadora-de-capacidad-hipotecaria",
    altLang: "es",
    calc: true,
  },
  {
    key: "affordability",
    path: "/es/calculadora-de-capacidad-hipotecaria",
    lang: "es",
    alt: "/de/immobilienbudget-rechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "affordability",
    path: "/de/immobilienbudget-rechner",
    lang: "de",
    alt: "/home-affordability-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "creditCard",
    path: "/credit-card-payoff-calculator",
    lang: "en",
    alt: "/es/calculadora-de-pago-de-tarjeta-de-credito",
    altLang: "es",
    calc: true,
  },
  {
    key: "creditCard",
    path: "/es/calculadora-de-pago-de-tarjeta-de-credito",
    lang: "es",
    alt: "/de/kreditkarten-tilgungsrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "creditCard",
    path: "/de/kreditkarten-tilgungsrechner",
    lang: "de",
    alt: "/credit-card-payoff-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "fd",
    path: "/fixed-deposit-calculator",
    lang: "en",
    alt: "/es/calculadora-de-plazo-fijo",
    altLang: "es",
    calc: true,
  },
  {
    key: "fd",
    path: "/es/calculadora-de-plazo-fijo",
    lang: "es",
    alt: "/de/festgeldrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "fd",
    path: "/de/festgeldrechner",
    lang: "de",
    alt: "/fixed-deposit-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "rd",
    path: "/recurring-deposit-calculator",
    lang: "en",
    alt: "/es/calculadora-de-deposito-recurrente",
    altLang: "es",
    calc: true,
  },
  {
    key: "rd",
    path: "/es/calculadora-de-deposito-recurrente",
    lang: "es",
    alt: "/de/ratensparrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "rd",
    path: "/de/ratensparrechner",
    lang: "de",
    alt: "/recurring-deposit-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "simple",
    path: "/simple-interest-calculator",
    lang: "en",
    alt: "/es/calculadora-de-interes-simple",
    altLang: "es",
    calc: true,
  },
  {
    key: "simple",
    path: "/es/calculadora-de-interes-simple",
    lang: "es",
    alt: "/de/zinsrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "simple",
    path: "/de/zinsrechner",
    lang: "de",
    alt: "/simple-interest-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "cagr",
    path: "/cagr-calculator",
    lang: "en",
    alt: "/es/calculadora-de-cagr",
    altLang: "es",
    calc: true,
  },
  {
    key: "cagr",
    path: "/es/calculadora-de-cagr",
    lang: "es",
    alt: "/de/cagr-rechner",
    altLang: "de",
    calc: true,
  },
  { key: "cagr", path: "/de/cagr-rechner", lang: "de", alt: "/cagr-calculator", altLang: "en", calc: true },
  {
    key: "retirement",
    path: "/retirement-calculator",
    lang: "en",
    alt: "/es/calculadora-de-jubilacion",
    altLang: "es",
    calc: true,
  },
  {
    key: "retirement",
    path: "/es/calculadora-de-jubilacion",
    lang: "es",
    alt: "/de/altersvorsorge-rechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "retirement",
    path: "/de/altersvorsorge-rechner",
    lang: "de",
    alt: "/retirement-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "savings",
    path: "/savings-goal-calculator",
    lang: "en",
    alt: "/es/calculadora-de-meta-de-ahorro",
    altLang: "es",
    calc: true,
  },
  {
    key: "savings",
    path: "/es/calculadora-de-meta-de-ahorro",
    lang: "es",
    alt: "/de/sparzielrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "savings",
    path: "/de/sparzielrechner",
    lang: "de",
    alt: "/savings-goal-calculator",
    altLang: "en",
    calc: true,
  },
  {
    key: "inflation",
    path: "/inflation-calculator",
    lang: "en",
    alt: "/es/calculadora-de-inflacion",
    altLang: "es",
    calc: true,
  },
  {
    key: "inflation",
    path: "/es/calculadora-de-inflacion",
    lang: "es",
    alt: "/de/inflationsrechner",
    altLang: "de",
    calc: true,
  },
  {
    key: "inflation",
    path: "/de/inflationsrechner",
    lang: "de",
    alt: "/inflation-calculator",
    altLang: "en",
    calc: true,
  },
  { key: "about", path: "/about", lang: "en", alt: "/es/acerca-de", altLang: "es", calc: false },
  { key: "about", path: "/es/acerca-de", lang: "es", alt: "/de/ueber-uns", altLang: "de", calc: false },
  { key: "about", path: "/de/ueber-uns", lang: "de", alt: "/about", altLang: "en", calc: false },
  { key: "terms", path: "/terms", lang: "en", alt: "/es/terminos", altLang: "es", calc: false },
  {
    key: "terms",
    path: "/es/terminos",
    lang: "es",
    alt: "/de/nutzungsbedingungen",
    altLang: "de",
    calc: false,
  },
  { key: "terms", path: "/de/nutzungsbedingungen", lang: "de", alt: "/terms", altLang: "en", calc: false },
  {
    key: "disclaimer",
    path: "/disclaimer",
    lang: "en",
    alt: "/es/descargo-de-responsabilidad",
    altLang: "es",
    calc: false,
  },
  {
    key: "disclaimer",
    path: "/es/descargo-de-responsabilidad",
    lang: "es",
    alt: "/de/haftungsausschluss",
    altLang: "de",
    calc: false,
  },
  {
    key: "disclaimer",
    path: "/de/haftungsausschluss",
    lang: "de",
    alt: "/disclaimer",
    altLang: "en",
    calc: false,
  },
  { key: "privacy", path: "/privacy", lang: "en", alt: "/es/privacidad", altLang: "es", calc: false },
  { key: "privacy", path: "/es/privacidad", lang: "es", alt: "/de/datenschutz", altLang: "de", calc: false },
  { key: "privacy", path: "/de/datenschutz", lang: "de", alt: "/privacy", altLang: "en", calc: false },
] as const;

/** Calculator pages only. */
export const CALC_PAGES = PAGES.filter((p) => p.calc);
